# Generated by Django 4.1.7 on 2023-04-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchases", "0014_company_tender_amount_company_total_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionOKVED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "okved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="purchases.okved",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="okveds",
                        to="purchases.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyRegionOKVED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.company",
                    ),
                ),
                (
                    "region_okved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistic.regionokved",
                    ),
                ),
            ],
        ),
    ]
