# Generated by Django 4.1.7 on 2023-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionokved",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="regionokved",
            name="sum",
            field=models.IntegerField(null=True),
        ),
    ]
