# Generated by Django 4.1.7 on 2023-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0003_alter_companyregionokved_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyregionokved",
            name="win_amount",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companyregionokved",
            name="win_price",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="companyregionokved",
            name="amount",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="companyregionokved",
            name="price",
            field=models.BigIntegerField(null=True),
        ),
    ]
