# Generated by Django 4.1.7 on 2023-04-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0014_company_tender_amount_company_total_price_and_more"),
        ("statistic", "0004_companyregionokved_win_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.BigIntegerField(null=True)),
                ("amount", models.BigIntegerField(null=True)),
                ("win_price", models.BigIntegerField(null=True)),
                ("win_amount", models.BigIntegerField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.company",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyOKVED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.BigIntegerField(null=True)),
                ("amount", models.BigIntegerField(null=True)),
                ("win_price", models.BigIntegerField(null=True)),
                ("win_amount", models.BigIntegerField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.company",
                    ),
                ),
                (
                    "okved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.okved",
                    ),
                ),
            ],
        ),
    ]
