# Generated by Django 4.1.7 on 2023-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpgz",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
