# Generated by Django 4.1.7 on 2023-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0005_alter_company_inn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=282),
        ),
    ]
