# Generated by Django 4.1.7 on 2023-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0009_alter_kpgz_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=350),
        ),
    ]
