# Generated by Django 4.1.7 on 2023-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0012_okved_kpgz_okved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="okved",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
