# Generated by Django 4.1.7 on 2023-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0013_alter_okved_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tender_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="win_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="win_price",
            field=models.IntegerField(default=0),
        ),
    ]
