# Generated by Django 4.1.7 on 2023-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0014_company_tender_amount_company_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="okved",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="okved",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="region",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="region",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
