# Generated by Django 4.1.7 on 2023-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0016_alter_okved_total_amount_alter_okved_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="competetors",
            field=models.ManyToManyField(
                null=True, related_name="rev_competetors", to="purchases.company"
            ),
        ),
    ]
